spring.application.name=BootprojFileMongoBD


spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=NTSP715DB
spring.data.mongodb.username=testuser
spring.data.mongodb.password=your_password
